name: Feature Request
description: Suggest an idea for Chappy
labels: ["needs grooming"]
body:
  - type: markdown
    attributes:
      value: |
        # Problem Statement
        _As a member I want an awesome new button so that I can do big things!_
  - type: dropdown
    id: user
    label: As a [user]
    options:
      - member
      - provider
      - member OR provider
    validations:
      required: true
  - type: input
    id: desire
    label: I want [feature]
    placeholder: an awesome new button
    validations:
      required: true
  - type: input
    id: outcome
    label: So that [outcome]
    placeholder: I can do big things!
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      value: '1. '
      label: Proposed Solution
      description: What should be built and how will it be used?
    validations:
      required: true
